substitutions:
  name: ks-602s
  friendly_name: "Unprovisioned KS-602S"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true
  project:
    name: "jrosenth.${name}"
    version: "1.0.0"

libretiny:
  board: generic-bk7231n-qfn32-tuya
  framework:
    version: dev

logger: {}
api: {}
ota: {}

dashboard_import:
  package_import_url: github://jackrosenthal/esphome-configs/ks_602s.yaml
  import_full_config: false

binary_sensor:
  - platform: gpio
    pin:
      number: P26
      mode:
        input: True
        pullup: True
      inverted: True
    id: main_button
    on_press:
      then:
        - light.toggle: light0

output:
  - platform: gpio
    pin: P17
    id: relay

light:
  - platform: binary
    output: relay
    name: "${friendly_name} Light"
    id: light0

status_led:
  pin:
    number: P24
    inverted: True
