substitutions:
  model: mfa03

packages:
  default: !include "../../common/default.yaml"

esp8266:
  board: esp01_1m

# P13L, P4L: Blue
# P13L, P4H: Green
# P13H, P4L: Off
# P13H, P4H: Green

binary_sensor:
  - platform: gpio
    pin:
      number: 0
      mode:
        input: True
        pullup: True
      inverted: True
    id: button0
    on_press:
      then:
        - light.toggle: light0
        - output.turn_on: vibrator0
        - delay: 50ms
        - output.turn_off: vibrator0

light:
  - platform: binary
    name: "Light"
    id: light0
    output: relay0
    on_turn_on:
      then:
        - output.turn_on: on_led
    on_turn_off:
      then:
        - output.turn_off: on_led

output:
  - platform: gpio
    pin: 12
    id: relay0
  - platform: gpio
    pin:
      number: 13
      inverted: True
    id: on_led
  - platform: gpio
    pin: 14
    id: vibrator0

status_led:
  pin: 4
