substitutions:
  model: mfa-06

packages:
  mfa-05: !include "mfa-05.yaml"

binary_sensor:
  - id: !extend main_button
    pin:
      number: 4
      mode:
        input: True
        pullup: True
      inverted: True
  - platform: gpio
    pin:
      number: 0
      mode:
        input: True
        pullup: True
      inverted: True
    id: secondary_button
    on_press:
      then:
        - switch.toggle: sw1

switch:
  - id: !extend sw0
    pin: 12
    name: "Output 1"
  - platform: gpio
    pin: 16
    name: "Output 2"
    id: sw1

output:
  - id: !remove motion_led
  - id: motion_led
    platform: template
    type: binary
    write_action: []

light:
  - id: !extend status
    pin:
      number: 13
      inverted: True
