substitutions:
  model: mfa-03

packages:
  default: !include "../../common/default.yaml"

esp8266:
  board: esp01_1m

# P13L, P4L: Blue
# P13L, P4H: Green
# P13H, P4L: Off
# P13H, P4H: Green

binary_sensor:
  - <<: !include "../../common/main_button.yaml"
    platform: gpio
    pin:
      number: 0
      mode: INPUT_PULLUP
      inverted: True

switch:
  - platform: gpio
    name: "Switch"
    id: sw0
    pin: 12
    on_turn_on:
      then:
        - output.turn_on: on_led
    on_turn_off:
      then:
        - output.turn_off: on_led

output:
  - platform: gpio
    pin:
      number: 13
      inverted: True
    id: on_led

status_led:
  pin: 4
