substitutions:
  model: sys-fs-01

packages:
  esp8266: !include "../../common/esp8266.yaml"

esphome:
  on_boot:
    priority: 800
    then:
      - delay: 20s
      - fan.turn_on:
          id: fan0
          speed: 1
      - delay: 100ms
      - fan.turn_off: fan0

script:
  - id: !remove main_button_press

logger:
  # Disable serial port (conflict with Tuya MCU).
  baud_rate: 0

uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600

tuya: {}

# Tuya:
#   Datapoint 1: switch (value: OFF)
#   Datapoint 3: enum (value: 0)
#   Datapoint 6: enum (value: 0)
#   Datapoint 7: int value (value: 0)
#   Product: '{"p":"rviyyhbek17aamye","v":"1.0.0","m":0}'

fan:
  - platform: "tuya"
    name: "Fan"
    id: fan0
    switch_datapoint: 1
    speed_datapoint: 3
    speed_count: 4
