substitutions:
  name: br2-dim1
  friendly_name: "Bedroom 2"
  ip_address: 10.10.12.10

packages:
  ks-d01w: !include "../../models/bk7231n/ks-d01w.yaml"
  static_ip: !include "../../common/static_ip.yaml"
