substitutions:
  name: br3-dim1
  friendly_name: "Bedroom 3"
  ip_address: 10.10.12.11

packages:
  ks-d01w: !include "../../models/bk7231n/ks-d01w.yaml"
  static_ip: !include "../../common/static_ip.yaml"
