substitutions:
  name: lof-dim2
  friendly_name: "Loft Hall RHS"
  ip_address: 10.10.12.13

packages:
  ks-d01w: !include "../../models/bk7231n/ks-d01w.yaml"
  static_ip: !include "../../common/static_ip.yaml"
