substitutions:
  name: lof-dim3
  friendly_name: "Loft Stairs LHS"
  ip_address: 10.10.12.17

packages:
  ks-d01w: !include "../../models/bk7231n/ks-d01w.yaml"
  static_ip: !include "../../common/static_ip.yaml"
