substitutions:
  name: br1-dim1
  friendly_name: "Bedroom 1 Door RHS"
  ip_address: 10.10.12.21

packages:
  ks-d01w: !include "../../models/bk7231n/ks-d01w.yaml"
  static_ip: !include "../../common/static_ip.yaml"
