substitutions:
  name: br1-mb4
  friendly_name: "Bedroom 1 Vanity LHS"
  ip_address: 10.10.12.25

packages:
  moes-ws-b-us: !include "../../models/bk7231n/moes-ws-b-us.yaml"
  static_ip: !include "../../common/static_ip.yaml"
  sw1_is_a_light: !include "../../common/sw1_is_a_light.yaml"

light:
  - id: !extend sw1_light
    name: Sconces
