substitutions:
  name: ent-mb1
  friendly_name: "Front Door RHS"
  ip_address: 10.10.12.28

packages:
  moes-ws-b-us: !include "../../models/bk7231n/moes-ws-b-us.yaml"
  static_ip: !include "../../common/static_ip.yaml"
  sw1_is_a_light: !include "../../common/sw1_is_a_light.yaml"
  sw2_is_a_light: !include "../../common/sw2_is_a_light.yaml"

light:
  - id: !extend sw1_light
    name: Front Door Ext Cans
  - id: !extend sw2_light
    name: Front Door Ext Sconce
