substitutions:
  name: ent-mb2
  friendly_name: "Entry Downstairs LHS"
  ip_address: 10.10.12.29

packages:
  moes-ws-b-us: !include "../../models/bk7231n/moes-ws-b-us.yaml"
  static_ip: !include "../../common/static_ip.yaml"
