substitutions:
  name: ent-dim3
  friendly_name: "Door to garage inside"
  ip_address: 10.10.12.31

packages:
  ks-d01w: !include "../../models/bk7231n/ks-d01w.yaml"
  static_ip: !include "../../common/static_ip.yaml"
