substitutions:
  name: gre-dim1
  friendly_name: "Dining LHS"
  ip_address: 10.10.12.36

packages:
  ks-d01w: !include "../../models/bk7231n/ks-d01w.yaml"
  static_ip: !include "../../common/static_ip.yaml"
