substitutions:
  name: gre-mb1
  friendly_name: "Dining RHS"
  ip_address: 10.10.12.37

packages:
  moes-ws-b-us: !include "../../models/bk7231n/moes-ws-b-us.yaml"
  static_ip: !include "../../common/static_ip.yaml"
