substitutions:
  name: gre-dim4
  friendly_name: "Kitchen RHS"
  ip_address: 10.10.12.40

packages:
  ks-d01w: !include "../../models/bk7231n/ks-d01w.yaml"
  static_ip: !include "../../common/static_ip.yaml"
