substitutions:
  name: gre-dim7
  friendly_name: "Living by patio door RHS"
  ip_address: 10.10.12.44

packages:
  ks-d01w: !include "../../models/bk7231n/ks-d01w.yaml"
  static_ip: !include "../../common/static_ip.yaml"
