substitutions:
  name: gre-dim8
  friendly_name: "Living by sliders RHS"
  ip_address: 10.10.12.46

packages:
  ks-d01w: !include "../../models/bk7231n/ks-d01w.yaml"
  static_ip: !include "../../common/static_ip.yaml"
