substitutions:
  name: pan-dim2
  friendly_name: "Pantry RHS"
  ip_address: 10.10.12.48

packages:
  ks-d01w: !include "../../models/bk7231n/ks-d01w.yaml"
  static_ip: !include "../../common/static_ip.yaml"
