substitutions:
  name: bas-dim1
  friendly_name: "Basement by stairs RHS"
  ip_address: 10.10.12.50

packages:
  ks-d01w: !include "../../models/bk7231n/ks-d01w.yaml"
  static_ip: !include "../../common/static_ip.yaml"
