substitutions:
  name: net-ms1
  friendly_name: "Net Closet"
  ip_address: 10.10.12.53
  timeout: 5 min

packages:
  mfa-05: !include "../../models/esp8266/mfa-05.yaml"
  static_ip: !include "../../common/static_ip.yaml"
  sw0_is_a_light: !include "../../common/sw0_is_a_light.yaml"
