substitutions:
  name: bas-dim3
  friendly_name: "Basement Hall RHS"
  ip_address: 10.10.12.56

packages:
  ks-d01w: !include "../../models/bk7231n/ks-d01w.yaml"
  static_ip: !include "../../common/static_ip.yaml"
