substitutions:
  name: br5-ms1
  friendly_name: "Bedroom 5 closet"
  ip_address: 10.10.12.61

packages:
  mfa-05: !include "../../models/esp8266/mfa-05.yaml"
  static_ip: !include "../../common/static_ip.yaml"
  sw0_is_a_light: !include "../../common/sw0_is_a_light.yaml"
