substitutions:
  switch_id: sw0
  restart_id: restart_btn
  safe_mode_id: safe_mode_btn
  factory_reset_id: factory_reset_btn
  name: "${model}"
  friendly_name: "${model}"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true

packages:
  site_config: !include "../site_config.yaml"

ota:
  - platform: esphome
    id: esphome_ota

update:

network: {}
logger: {}
api: {}
mdns: {}
captive_portal: {}
wifi:
  power_save_mode: NONE
  ap: {}
web_server:
  port: 80

script:
  - id: main_button_press
    mode: single
    then:
      - switch.toggle: "${switch_id}"

button:
  - platform: restart
    name: "Restart"
    id: "${restart_id}"
    disabled_by_default: True
  - platform: safe_mode
    name: "Safe Mode"
    id: "${safe_mode_id}"
    disabled_by_default: True
