# Jiangsu Barep BAA-032
# https://www.alibaba.com/product-detail/US-Wall-mounted-smart-power-socket_1600732086091.html

substitutions:
  model: baa-032

packages:
  default: !include "../../common/default.yaml"

bk72xx:
  board: cb2s
  framework:
    version: dev

binary_sensor:
  - <<: !include "../../common/main_button.yaml"
    platform: gpio
    pin:
      number: P24
      mode:
        input: True
        pullup: True
      inverted: True

switch:
  - platform: gpio
    pin: P26
    name: "${friendly_name} AC Outlets"
    id: sw0
    icon: mdi:power-socket-us
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: gpio
    pin: P8
    name: "${friendly_name} USB Ports"
    id: sw1
    icon: mdi:usb
    restore_mode: RESTORE_DEFAULT_ON

status_led:
  pin:
    number: P6
    inverted: True
