substitutions:
  model: ds-122

packages:
  default: !include "../../common/default.yaml"

bk72xx:
  board: wb3s
  framework:
    version: dev

binary_sensor:
  - platform: gpio
    pin:
      number: P10
      mode:
        input: True
        pullup: True
      inverted: True
    id: button
    on_press:
      then:
        - light.toggle: light0

output:
  - platform: gpio
    pin:
      number: P26
      inverted: True
    id: blue_led
  - platform: gpio
    pin: P6
    id: relay

light:
  - platform: binary
    output: relay
    id: light0
    name: "${friendly_name} Light"
    on_turn_on:
      then:
        - output.turn_on: blue_led
    on_turn_off:
      then:
        - output.turn_off: blue_led

status_led:
  pin:
    number: P1
    inverted: True
