substitutions:
  model: feit-dimwifi-cb2s

packages:
  bk72xx: !include "../../common/bk72xx.yaml"

bk72xx:
  board: cb2s

script:
  - id: !remove main_button_press

logger:
  # Disable serial port (conflict with Tuya MCU).
  baud_rate: 0

uart:
  rx_pin: P10
  tx_pin: P11
  baud_rate: 9600

tuya: {}

light:
  - platform: "tuya"
    id: "dimmer"
    name: "Dimmer"
    dimmer_datapoint: 2
    switch_datapoint: 1
    min_value: 10
    max_value: 1000
