substitutions:
  model: fl-s122b

packages:
  default: !include "../../common/default.yaml"

bk72xx:
  board: cbu
  framework:
    version: dev

binary_sensor:
  - <<: !include "../../common/main_button.yaml"
    platform: gpio
    pin:
      number: P14
      mode: INPUT_PULLUP
      inverted: True
  - platform: gpio
    pin:
      number: P16
      mode: INPUT_PULLUP
      inverted: True
    id: btn2
    name: "Button 2"
    on_press:
      then:
        - switch.toggle: sw1
  - platform: gpio
    pin:
      number: P9
      mode: INPUT_PULLUP
      inverted: True
    id: btn3
    name: "Button 3"
    on_press:
      then:
        - switch.toggle: sw2

output:
  - platform: gpio
    pin: P20
    id: led0
  - platform: gpio
    pin: P8
    id: led1
  - platform: gpio
    pin: P28
    id: led2

switch:
  - platform: gpio
    id: sw0
    pin: P6
    name: "Switch 1"
    on_turn_on:
      - output.turn_on: led0
    on_turn_off:
      - output.turn_off: led0
  - platform: gpio
    id: sw1
    pin: P26
    name: "Switch 2"
    on_turn_on:
      - output.turn_on: led1
    on_turn_off:
      - output.turn_off: led1
  - platform: gpio
    id: sw2
    pin: P24
    name: "Switch 3"
    on_turn_on:
      - output.turn_on: led2
    on_turn_off:
      - output.turn_off: led2
