# This is firmware for a number of Tuya Smart Plugs with CB2S module.
# Cloudcutter profile: qncx-16a-smart-plug
#
# Chengdu Xugang XGWiFi-01 Smart Plug
# "QNCX" brand on AliExpress
# https://www.aliexpress.us/item/3256805074476065.html
#
# Jiangsu Barep BSC-004
# https://www.alibaba.com/product-detail/Smart-Plug-2022-Hot-Sale-Wifi_1600447954354.html
#
# ZN35780201
# https://www.aliexpress.us/item/3256805078682340.html
#
# Pins:
#   P6: !Red LED (not present on some plugs?)
#   P7: !Blue LED
#   P8: Button (active low)
#   P24: Relay (active high)

substitutions:
  model: generic-cb2s-smart-plug

packages:
  bk72xx: !include "../../common/bk72xx.yaml"

bk72xx:
  board: cb2s

binary_sensor:
  - <<: !include "../../common/main_button.yaml"
    platform: gpio
    pin:
      number: P8
      mode:
        input: True
        pullup: True
      inverted: True

output:
  - platform: gpio
    pin:
      number: P7
      inverted: True
    id: led

switch:
  - platform: gpio
    pin: P24
    id: sw0
    name: "Smart Plug"
    on_turn_on:
      then:
        - output.turn_on: led
    on_turn_off:
      then:
        - output.turn_off: led

status_led:
  pin:
    number: P6
    inverted: True
