# This is firmware for a number of Tuya Smart Plugs with CB2S module.
# Cloudcutter profile: qncx-16a-smart-plug
#
# Chengdu Xugang XGWiFi-01 Smart Plug
# "QNCX" brand on AliExpress
# https://www.aliexpress.us/item/3256805074476065.html
#
# Jiangsu Barep BSC-004
# https://www.alibaba.com/product-detail/Smart-Plug-2022-Hot-Sale-Wifi_1600447954354.html
#
# ZN35780201
# https://www.aliexpress.us/item/3256805078682340.html
#
# Pins:
#   P6: !Red LED (not present on some plugs?)
#   P7: !Blue LED
#   P8: Button (active low)
#   P24: Relay (active high)

substitutions:
  model: generic-cb2s-smart-plug

packages:
  default: !include "../../common/default.yaml"

bk72xx:
  board: generic-bk7231n-qfn32-tuya
  framework:
    version: dev

binary_sensor:
  - platform: gpio
    pin:
      number: P8
      mode:
        input: True
        pullup: True
      inverted: True
    id: button
    on_press:
      then:
        - switch.toggle: relay

output:
  - platform: gpio
    pin:
      number: P7
      inverted: True
    id: led

switch:
  - platform: gpio
    pin: P24
    id: relay
    name: "Smart Plug"
    on_turn_on:
      then:
        - output.turn_on: led
    on_turn_off:
      then:
        - output.turn_off: led

status_led:
  pin:
    number: P6
    inverted: True
