substitutions:
  model: ks-602s

packages:
  bk72xx: !include "../../common/bk72xx.yaml"

bk72xx:
  board: generic-bk7231n-qfn32-tuya

binary_sensor:
  - <<: !include "../../common/main_button.yaml"
    platform: gpio
    pin:
      number: P26
      mode:
        input: True
        pullup: True
      inverted: True

switch:
  - platform: gpio
    pin: P17
    name: "Switch"
    id: sw0

status_led:
  pin:
    number: P24
    inverted: True
