# Hidintech KS-604S Smart Outlet with USB
#
# .---------.
# |  |   |  |    Relay: P26
# |    o    |
# | B  L  U |    Button: P11, Red LED: Hard-wire to relay high
# |    L  S |    Green LED: P10 Active Low, USB port: P6
# | B  L  B |    Button: P26, Red LED: Hard-wire to relay high
# |  |   |  |
# |    o    |    Relay: P8
# `---------'

substitutions:
  model: ks-604s
  switch_id: upper_outlet

packages:
  bk72xx: !include "../../common/bk72xx.yaml"

bk72xx:
  board: generic-bk7231n-qfn32-tuya

binary_sensor:
  - <<: !include "../../common/main_button.yaml"
    platform: gpio
    pin: P11
  - platform: gpio
    pin: P24
    id: lower_button
    on_press:
      then:
        - switch.toggle: lower_outlet

switch:
  - platform: gpio
    pin: P26
    name: "Upper Outlet"
    id: upper_outlet
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: gpio
    pin: P8
    name: "Lower Outlet"
    id: lower_outlet
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: gpio
    pin: P6
    id: usb
    name: "USB Port"
    restore_mode: RESTORE_DEFAULT_ON

status_led:
  pin:
    number: P10
    inverted: True
