# Hidintech KS-602F - BK7231N variant

substitutions:
  model: ks-602f

packages:
  default: !include "../../common/default.yaml"

bk72xx:
  board: generic-bk7231n-qfn32-tuya
  framework:
    version: dev

binary_sensor:
  - <<: !include "../../common/main_button.yaml"
    platform: gpio
    pin:
      number: P24
      mode:
        input: True
        pullup: True
      inverted: True
  - platform: gpio
    pin: P17
    id: is_on
    on_press:
      - switch.turn_on: sw0
    on_release:
      - switch.turn_off: sw0

switch:
  - platform: gpio
    pin: P26
    id: relay
  - platform: output
    output: virtual_output
    name: "Switch"
    id: sw0

output:
  - platform: template
    type: binary
    id: virtual_output
    write_action:
      - if:
          condition:
            - lambda: "return state;"
            - binary_sensor.is_off: is_on
          then:
            - switch.toggle: relay
      - if:
          condition:
            - lambda: "return !state;"
            - binary_sensor.is_on: is_on
          then:
            - switch.toggle: relay

status_led:
  pin:
    number: P22
    inverted: True
