substitutions:
  model: ks-7012

packages:
  default: !include "../../common/default.yaml"

bk72xx:
  board: generic-bk7231n-qfn32-tuya
  framework:
    version: dev

logger:
  # Disable serial port (conflict with Tuya MCU).
  baud_rate: 0

uart:
  rx_pin: P10
  tx_pin: P11
  baud_rate: 115200

tuya: {}

light:
  - platform: "tuya"
    id: "dimmer"
    name: "${friendly_name} Dimmer"
    dimmer_datapoint: 2
    switch_datapoint: 1
    min_value: 0
    max_value: 980
