substitutions:
  model: ks-d01w

packages:
  default: !include "../../common/default.yaml"

esphome:
  on_loop:
    then:
      lambda: !lambda |-
        float brightness;

        id(dimmer).current_values_as_brightness(&brightness);
        brightness = powf(brightness, 1 / 2.8);

        if (brightness >= 0.999)
          id(led5).turn_on();
        else
          id(led5).turn_off();

        if (brightness >= 0.749)
          id(led4).turn_on();
        else
          id(led4).turn_off();

        if (brightness >= 0.5)
          id(led3).turn_on();
        else
          id(led3).turn_off();

        if (brightness >= 0.25)
          id(led2).turn_on();
        else
          id(led2).turn_off();

bk72xx:
  board: cbu
  framework:
    version: dev

script:
  - id: !remove main_button_press
  - id: main_button_press
    mode: single
    then:
      - light.toggle: dimmer

binary_sensor:
  - <<: !include "../../common/main_button.yaml"
    platform: gpio
    pin:
      number: P9
      mode:
        input: True
        pullup: True
      inverted: True
  - platform: gpio
    pin:
      number: P20
      mode:
        input: True
        pullup: True
      inverted: True
    id: brightness_down_button
    filters:
      autorepeat:
        - delay: 500ms
          time_off: 15ms
          time_on: 485ms
    on_press:
      then:
        - if:
            condition:
              light.is_on: dimmer
            then:
              - light.dim_relative:
                  id: dimmer
                  relative_brightness: -10%
            else:
              - light.turn_on:
                  id: dimmer
                  brightness: 1%
  - platform: gpio
    pin:
      number: P22
      mode:
        input: True
        pullup: True
      inverted: True
    id: brightness_up_button
    filters:
      autorepeat:
        - delay: 500ms
          time_off: 15ms
          time_on: 485ms
    on_press:
      then:
        - if:
            condition:
              light.is_on: dimmer
            then:
              - light.dim_relative:
                  id: dimmer
                  relative_brightness: +10%
            else:
              - light.turn_on:
                  id: dimmer
                  brightness: 100%

output:
  - platform: libretiny_pwm
    pin: P8
    id: pwm_output
    min_power: 0.15
    max_power: 0.999
  - platform: gpio
    pin: P14
    id: led1
  - platform: gpio
    pin: P16
    id: led2
  - platform: gpio
    pin: P7
    id: led3
  - platform: gpio
    pin: P6
    id: led4
  - platform: gpio
    pin: P26
    id: led5

light:
  - platform: monochromatic
    output: pwm_output
    name: "Light"
    id: dimmer
    on_turn_on:
      - output.turn_on: led1
    on_turn_off:
      - output.turn_off: led1

status_led:
  pin: P17
