# Zitech TH08 Wi-Fi Temperature & Humidity Sensor
# https://expo.tuya.com/product/1077042
# Product ID: xlk3mtpjo1zkmdvh

substitutions:
  model: th08

packages:
  bk72xx: !include "../../common/bk72xx.yaml"

bk72xx:
  board: cbu

script:
  - id: !remove main_button_press

logger:
  # Disable serial logging (conflict with Tuya MCU).
  baud_rate: 0

uart:
  rx_pin: D10
  tx_pin: D11
  baud_rate: 9600

tuya: {}
