substitutions:
  model: "ysdm102-cb3s"

packages:
  default: !include "../../common/default.yaml"

bk72xx:
  board: cb3s
  framework:
    version: dev

logger:
  # Disable UART for Tuya MCU.
  baud_rate: 0

tuya: {}

uart:
  rx_pin: P10
  tx_pin: P11
  baud_rate: 115200

sn74hc595:
  - id: hc595
    data_pin: P14
    clock_pin: P24
    latch_pin: P26
    sr_count: 8

switch:
  - platform: gpio
    name: "HC595 Pin #0"
    pin:
      sn74hc595: hc595
      number: 0
  - platform: gpio
    name: "HC595 Pin #1"
    pin:
      sn74hc595: hc595
      number: 1
  - platform: gpio
    name: "HC595 Pin #2"
    pin:
      sn74hc595: hc595
      number: 2
  - platform: gpio
    name: "HC595 Pin #3"
    pin:
      sn74hc595: hc595
      number: 3
  - platform: gpio
    name: "HC595 Pin #4"
    pin:
      sn74hc595: hc595
      number: 4
  - platform: gpio
    name: "HC595 Pin #5"
    pin:
      sn74hc595: hc595
      number: 5
  - platform: gpio
    name: "HC595 Pin #6"
    pin:
      sn74hc595: hc595
      number: 6
  - platform: gpio
    name: "HC595 Pin #7"
    pin:
      sn74hc595: hc595
      number: 7

binary_sensor:
  - platform: gpio
    pin:
      number: P8
      mode: INPUT_PULLUP
      inverted: True
    id: increase_brightness_btn
  - platform: gpio
    pin:
      number: P0
      mode: INPUT_PULLUP
      inverted: True
    id: decrease_brightness_btn
  - platform: gpio
    pin:
      number: P23
      mode: INPUT_PULLUP
      inverted: True
    id: main_button

light:
  - platform: tuya
    id: "dimmer"
    name: "Dimmer"
    dimmer_datapoint: 2
    switch_datapoint: 1
    min_value: 10
    max_value: 1000

status_led:
  pin: P7
