substitutions:
  name: computer-lab-closet-light
  friendly_name: "Computer Lab Closet Light"
  ip_address: 10.10.10.31

packages:
  athom_mini_switch: !include "../../models/esp8266/athom-mini-switch.yaml"
  static_ip: !include "../../common/static_ip.yaml"
  sw0_is_a_light: !include "../../common/sw0_is_a_light.yaml"
