substitutions:
  name: garage-mfa-06
  friendly_name: "Garage MFA-06"
  ip_address: 10.10.10.29
  timeout: 5 minutes

packages:
  mfa-06: !include "../../models/esp8266/mfa-06.yaml"
  static_ip: !include "../../common/static_ip.yaml"
  sw0_is_a_light: !include "../../common/sw0_is_a_light.yaml"
  sw1_is_a_light: !include "../../common/sw1_is_a_light.yaml"

light:
  - id: !extend sw0_light
    name: Garage Light
  - id: !extend sw1_light
    name: Garage Outdoor Lights
