substitutions:
  name: guest-bathroom-exhaust-fan
  friendly_name: "Guest Bathroom Exhaust Fan"
  ip_address: 10.10.10.25

packages:
  ks-602s: !include "../../models/bk7231n/ks-602s.yaml"
  static_ip: !include "../../common/static_ip.yaml"
  sw0_is_a_fan: !include "../../common/sw0_is_a_fan.yaml"
