# ATARM LS01 / DS-128 Light Switch
# https://www.atarm.com/product-page/ls01
# https://www.aliexpress.us/item/3256805457749476.html
# Cloudcutter profile: oem-bk7231s-rnd-switch-1.0.7-sdk-2.0.0-30.06
# LED:
#   White: P6, Active Low
#   Green: P10, Active Low
# Button: P7, Active Low
# Relay: P26, Active High

substitutions:
  model: ds-128

packages:
  default: !include "../../common/default.yaml"

bk72xx:
  board: wb2s
  framework:
    version: dev

binary_sensor:
  - <<: !include "../../common/main_button.yaml"
    platform: gpio
    pin:
      number: P7
      mode:
        input: True
        pullup: True
      inverted: True

output:
  - platform: gpio
    pin:
      number: P10
      inverted: True
    id: green_led

switch:
  - platform: gpio
    pin: P26
    id: sw0
    name: "${friendly_name} Light"
    on_turn_on:
      then:
        - output.turn_on: green_led
    on_turn_off:
      then:
        - output.turn_off: green_led

status_led:
  pin:
    number: P6
    inverted: True
