substitutions:
  model: ds-122

packages:
  bk72xx: !include "../../common/bk72xx.yaml"

bk72xx:
  board: wb3s

binary_sensor:
  - <<: !include "../../common/main_button.yaml"
    platform: gpio
    pin:
      number: P10
      mode:
        input: True
        pullup: True
      inverted: True

output:
  - platform: gpio
    pin:
      number: P26
      inverted: True
    id: blue_led

switch:
  - platform: gpio
    pin: P6
    id: sw0
    name: "Switch"
    on_turn_on:
      then:
        - output.turn_on: blue_led
    on_turn_off:
      then:
        - output.turn_off: blue_led

status_led:
  pin:
    number: P1
    inverted: True
